# change file name to "compose.yml" in order to use
# command: mv compose_example.yml compose.yml

services:
  flame:
    image: ghcr.io/fdarveau/flame:latest
    container_name: flame
    volumes:
      - ./flame/:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PASSWORD= # provide Password
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-flame
    restart: unless-stopped
    depends_on:
      - flame
    ports:
      - "5005:5005"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - /docker/tailscale-certs:/etc/nginx/certs:ro # absolute path
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /var/tmp