# change file name to "compose.yml" in order to use
# command: mv compose_example_Nvidia.yml compose.yml

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC                    # enter your timezone
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./config:/config
      - /srv/dev-disk-by-uuid-__________/Videos:/data/Videos
      - /srv/dev-disk-by-uuid-__________/Shows:/data/Shows
      - /srv/dev-disk-by-uuid-__________/Music:/data/Music
      - /srv/dev-disk-by-uuid-__________/Movies:/data/Movies
      - /srv/dev-disk-by-uuid-__________/Photos:/data/Pictures
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

  nginx:
    image: nginx:alpine
    container_name: nginx-jellyfin
    restart: unless-stopped
    depends_on:
      - jellyfin
    ports:
      - "8096:8096" # choose port (both)
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - /docker/tailscale-certs:/etc/nginx/certs:ro # absolute path
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /var/tmp

# gpu documentation: https://jellyfin.org/docs/general/administration/hardware-acceleration/nvidia
