# change file name to "compose.yml" in order to use
# command: mv compose_example_mullvad.yml compose.yml

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=____________________  # input private key
      - WIREGUARD_ADDRESSES=__.__.__.__/32          # input address
      - WIREGUARD_ENDPOINT_PORT=51820               # Port can be changed in Mullvad config generator
      - SERVER_CITIES=Atlanta GA                    # input city
    volumes:
      - ./gluetun:/gluetun
    ports:
      # Mullvad disabled port forwarding (switch to airvpn if you want to seed)
      - 6901:6901/tcp # nginx https
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --timeout=5 https://1.1.1.1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

---
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000 # user id
      - PGID=1000 # group id
      - TZ=America/New_York
      - USER=______ # insert password (optional but recommended)
      - PASS=______ # insert password (optional but recommended)
    volumes:
       - ./transmission/data:/config
#      - /srv/dev-disk-by-uuid-____/downloads:/downloads
#   ports: # (handled by gluetun)   # DO NOT UNCOMMENT THESE PORTS!
#     - 9091:9091/tcp
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun" # Use gluetun's network
    
---
services:
  mullvad-browser:
    image: lscr.io/linuxserver/mullvad-browser:latest
    container_name: mullvad-browser
    cap_add:
      - NET_ADMIN
    security_opt:
    - seccomp:unconfined #optional
    environment:
      - PUID=1000 # user id
      - PGID=1000 # group id
      - TZ=Etc/UTC # timezeon
      - CUSTOM_USER=______   # insert password (optional but recommended)
      - PASSWORD=______   # insert password (optional but recommended)
    volumes:
      - ./mullvad-browser/config:/config
#    ports: # (handled by gluetun)   #   DO NOT UNCOMMENT THIS PORT!
#     - 6901:3001/tcp https port
    shm_size: "1gb"
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun" # Use gluetun's network

---
  nginx:
    image: nginx:alpine
    container_name: nginx-privacy
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - /docker/tailscale-certs:/etc/nginx/certs:ro # absolute path
    restart: unless-stopped