# change file name to "compose.yml" in order to use
# command: mv compose_nvidia.yml compose.yml
services:
  owncast:
    image: ich777/owncast:latest
    container_name: owncast
    restart: unless-stopped
    ports:
      - "1935:1935"   # RTMP ingest
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    volumes:
      - ./data:/owncast/data   # Persistent data storage
      - ./ffmpeg:/usr/local/bin/ffmpeg
    runtime: nvidia

  nginx:
    image: nginx:alpine
    container_name: nginx-owncast
    restart: unless-stopped
    depends_on:
      - owncast
    ports:
      - "1930:1930" # choose port (both)
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - /docker/tailscale-certs:/etc/nginx/certs:ro # absolute path
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /var/tmp