services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    environment:
      - TZ=America/New_York
    volumes:
      - ./data:/config
    ports:
      - "8200:8123"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-homeassistant
    restart: unless-stopped
    depends_on:
      - homeassistant
    ports:
      - "8125:8125"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - /docker/tailscale-certs:/etc/nginx/certs:ro # absolute path
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /var/tmp
