# change file name to "compose.yml" in order to use
# command: mv compose_example.yml compose.yml

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - DOMAIN=https://*machine_name*.tail-scale.ts.net:8901 # INPUT YOUR Tailscale MagicDNS URL - including port # (example displayed)
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=true                                         # Change to "false" after sign up
#     - WEB_VAULT_ENABLED=true                                      # web-vault (optional)
#     - WEB_VAULT_FOLDER=web-vault/                                 # web-vault folder
    volumes:
      - ./vw-data:/data
#      - ./bw_web_builds/container_builds/web-vault:/web-vault:ro    # web-vault (optional) ~ (":ro" means read-only)
    
  nginx:
    image: nginx:alpine
    container_name: nginx-vaultwarden
    restart: unless-stopped
    depends_on:
      - vaultwarden
    ports:
      - "8901:8901" # choose port (both)
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - /docker/tailscale-certs:/etc/nginx/certs:ro # absolute path
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /var/tmp
      
# to setup web_vault: https://github.com/dani-garcia/vaultwarden/wiki/Building-binary#install-the-web-vault
# once completed remove # for "web-builds" line and relaunch container.
